# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc993945ce9d406025687b5e6669460e024ee1b6ed33418568da392c49df30f62be7ea72260aa23432c8ddc609c62582fbe207860a5a654db1c5a703c5925549

test:
  secret_key_base: 2c2536244de76270ed8ec4ea73b259c62e6aad7a61ea971004a9e39762bc24e6161417fff6ddda3e96a8bd2a3b551f97959378d5bace74da51997fc83ba46128

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
